-- Este script cria a tabela 'TB_CLIENTE' no Oracle.
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- ID Coluna para o identificador único do usuário.
    -- NUMBER é o tipo de dado numérico padrão do Oracle.
    -- GENERATED BY DEFAULT  indica que o valor da coluna será gerado automaticamente pelo Oracle
    -- ON NULL A cláusula ON NULL significa que o Oracle gerará um valor para a coluna somente se o valor for explicitamente NULL durante a inserção
    -- AS IDENTITY Esta cláusula é a que, de fato, transforma a coluna em uma coluna auto-incrementável. Ela informa ao Oracle para usar um mecanismo de sequência para gerar valores sequenciais.
    NOME VARCHAR2(100) NOT NULL,
    -- NOME Coluna para o nome do usuário.
    -- VARCHAR2(100) armazena uma string de até 100 caracteres.
    -- NOT NULL garante que esta coluna nao pode ser vazia.
    SOBRENOME VARCHAR2(100) NOT NULL,
    -- SOBRENOME Coluna para o sobrenome do usuário.
    -- VARCHAR2(100) armazena uma string de até 100 caracteres.
    -- NOT NULL garante que esta coluna nao pode ser vazia.
    CONSTRAINT PK_TB_CLIENTE PRIMARY KEY (ID_CLIENTE)
    -- Adiciona uma restrição de chave primária para a tabela.
    -- PRIMARY KEY Define esta coluna como a chave primária da tabela, garantindo que cada valor seja único.
);

--Insere dados
--INSERT INTO TB_CLIENTE (NOME, SOBRENOME) VALUES ('FABIO','SILVA');

--Retorna os dados
--SELECT * FROM  TB_CLIENTE;

-- Apagar a Tabela
--DROP TABLE TB_CLIENTE;